---

apiVersion: apps/v1
kind: Deployment
metadata:
  type: Deployment
  app: mkdocs
spec:
  replicas: 2
  selector:
    pod: mkdocs
  template:
    metadata:
      pod: mkdocs
      type: Pod
    spec:
      containers:
        - name: mkdocs
          image: localhost:8000/mkdocs
          ports:
            - containerPort: 80 # container is listening for incoming traffic on prot 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      
---

apiVersion: v1
kind: Service
metadata:
  name: mkdocs-svc
  labels:
    app: mkdocs
    type: Service
spec:
  # type: ClusterIP
  type: NodePort
  selector:
    pod: mkdocs
  ports:
    - port: 80 # port exposed by service
      targetPort: 80 # port on which container is listening
      nodePort: 30008
