name: Meridian Docs

on:
 push:
   branches:
     - main

env:
  SERVER_IP: ""
  SERVER_USER: "" # server IP and user can be stored in github vars
  REPOSITORY_URL: "<my-server-two-url>:5000"
  EXISTING_CONTAINER: "meridian"

# echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

jobs:
   build-and-push:
    runs-on: self-hosted
    outputs:
      image_tag: ${{ steps.output-tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set image tags
        id: tags
        run: |
          echo "COMMIT_SHA_TAG=${{ github.sha }}" >> "$GITHUB_ENV"

      - name: Build the image
        id: output-tag
        run: |
           IMAGE= "${REPOSITORY_URL}/meridian:${{ github.sha }}"
           # docker build -t "${REPOSITORY_URL}/meridian-${{ steps.tags.outputs.COMMIT_SHA_TAG }}" ./
           docker build -t "$IMAGE" ./
           docker push "$IMAGE"
           echo "image_tag=$IMAGE" >> "$GITHUB_OUTPUT"

    deploy:
      runs-on: self-hosted
      needs: [build-and-push]
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
      steps:
        - name: SSH to website server and start new container
          run: |
            # Set up the SSH key securely
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            
            # Using an unquoted EOF allows variables like $SERVER_USER to be evaluated 
            # by the GitHub runner BEFORE sending the script to the remote server.
            ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" << EOF
              echo "Connected to \$(hostname)"
              
              # Safely stop and remove the container if it exists
              docker rm -f $EXISTING_CONTAINER || true
              
              # Pull and run the new image
              docker pull $REPOSITORY_URL/${{ needs.build-and-push.outputs.image_tag }}
              docker run -d -p 80:80 --name=$EXISTING_CONTAINER $REPOSITORY_URL/${{ needs.build-and-push.outputs.image_tag }}
              rm -f ~/.ssh/id_rsa
            EOF
